### ISSUE TITLE
介博哥你好 想知道static_framework是什么呢？

### ISSUE THREAD

**Issue by blackchena** [jaybowong/SwiftOCMixedPodWithLibAndFrameworkDependencies#1]
根据你们的讨论[Problems in a Swift-Objective-C-mixed static_framework pod, with vendor frameworks and libraries. ](https://github.com/CocoaPods/CocoaPods/issues/7307)，应该和xcode 9 static library support 相关，所以我觉得就是static library的framework表示形式。又疑惑

1.  xcode 9之前 含有swift 代码文件是不能编译成static library或者是 static framework的吗？
2. 含有swift代码的工程在用pod的时候必须要指定use_frameworks!，意思是这种工程不能依赖static library吗？还是只是pod不允许在podfile 里用pod 来引入带有static library的三方库(在工程中可以直接依赖 static library)。这种情况在现在pod version 1.4.0 在通过podfile pod 引入带有static library的三方库是可以的我这里是
```
    use_frameworks!
    pod 'UMCPush'
    pod 'UMCAnalytics'
    pod 'UMCErrorCatch'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCShare/Social/ReducedWeChat'
```
这种情况是把static library打包成dynamic library吗？
3，我在写自己的BLAFramework podspec的时候dependency了
```
      s.dependency 'UMCShare/Social/ReducedQQ'
      s.dependency 'UMCShare/Social/ReducedSina'
      s.dependency 'UMCShare/Social/ReducedWeChat'
```
在自己的demo中引入了
```
  use_frameworks!
  pod 'BLAFramework', :path => '../'
```
这个时候install 会出现target has transitive dependencies that include static binaries的错误为什么直接在podfile 里面引入上面几个库不会报错。把上面几个库加到私有pod里作为依赖会出现错误呢？
最后在自己的podspec里面加上了s.static_framework = true错误是消失咯，但这种情况只有pod 1.4.0以上且xcode 9.0以上能用static_framework吗？如果放在还不支持static_framework的时候这种问题如何解决呢？
小弟不才，在很久之前遇到过这个问题一直没有理解清楚，现在有被这些问题困扰了两天，看了很多cocoapods的issue 因为英文理解能力不行看起来很恼火，在看[Pod static framework dependency can't mix Swift and Objective-C](https://github.com/CocoaPods/CocoaPods/issues/7435)链接到咯你的[Problems in a Swift-Objective-C-mixed static_framework pod, with vendor frameworks and libraries.](https://github.com/CocoaPods/CocoaPods/issues/7307)很希望你能赐教，开发iOS这几年进步一直很慢，一直想进一个技术性较强的团队，但自己貌似能力达不到很多公司的要求(之前投过贵公司的简历)，哈哈希望你能看到这个issue吧。谢谢

**Comment by jaybowang** [comment]
@blackchena  不好意思，现在才看见，可能回复有点晚了，你都搞明白了

1.是的，Xcode 9才开始支持，可以看[Xcode Release Notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html)
2.`use_frameworks!`意思就是把那些pod库打包成dynamic framework，带有static library的库最终还是会打成dynamic framework
3.不太清楚现在最新版本是什么情况了，好像变化挺大的，最近没接触这块

**Comment by blackchena** [comment]
@jaybowong 哈哈 谢谢啦，也许搞清楚咯点，但是还是不明白为什么会必须显示设置s.static_framework = true
